graph TD
    AI[Kuenstliche Intelligenz] --> ML[Maschinelles Lernen]
    AI --> SKI[Symbolische KI / Regelbasiert]
    ML --> DL[Tiefes Lernen / Deep Learning]
    DL --> GenAI[Generative KI]
    
    AI -- Unterteilt in --> WeakAI[Schwache KI / ANI]
    AI -- Ziel --> StrongAI[Starke KI / AGI]
    StrongAI --> ASI[Superintelligenz]
    ASI --> Singularity[Singularitaet]
    
    WeakAI --- Turing[Turing-Test]
