graph LR
    CV[Computer Vision] --> Obj[Objekterkennung]
    CV --> Diff[Diffusionsmodelle / Bildgenerierung]
    
    Robot[Robotik] --> Hum[Humanoide Roboter]
    Hum --> VLA[VLA-Modell / Vision-Language-Action]
    
    Lernen[Lernen] --> Imit[Imitation Learning]
    Lernen --> S2R[Sim2Real]
    
    Mech[Mechanik] --> Akt[Aktuatoren / Muskeln]
    Mech --> Prop[Propriozeption / Koerpergefuehl]
