mindmap
  root((<b>AI BoM</b>))
    Basis-Modell
      Llama 3
      GPT-4
    Trainingsdaten
      Unternehmens-Wiki
      Kunden-Historie
    Frameworks
      LangChain
      PyTorch
    Sicherheit
      Red Teaming
      Guardrails
