graph TD
    W[<b>Handeln / Weisheit</b><br/>KI optimiert Prozesse] --- K[<b>Wissen</b><br/>Vernetzung im Wissensgraph]
    K --- I[<b>Information</b><br/>Strukturierte Daten]
    I --- D[<b>Daten</b><br/>Rohfakten / Zahlen]
    
    style W fill:#4CAF50,color:white
    style K fill:#8BC34A
    style I fill:#CDDC39
    style D fill:#F4FF81
